SELECT USER
FROM DUAL;
--==>> SCOTT

--○ 테이블 생성
CREATE TABLE TBL_MEMBERLIST
( ID    VARCHAR(30)
, PW    VARCHAR(20) NOT NULL
, NAME  VARCHAR(50) NOT NULL
, TEL   VARCHAR(50) NOT NULL
, EMAIL VARCHAR(100)
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
, CONSTRAINT MEMBERLIST_TEL_UK UNIQUE(TEL)
);
--==>> Table TBL_MEMBERLIST이(가) 생성되었습니다.


